### ISSUE TITLE
Make Meganeura egg give item with scroll wheel.

### ISSUE THREAD

**Issue by Anaghold** [EversongMill/Genesis#72]
Meganeura egg should give Meganeura egg item when we use scroll wheel in creative.

**Comment by The-Fireplace** [comment]
Woah. Didn't mean to unassign them, but I guess there wasn't any other way, since I can't re-assign them.

**Comment by The-Fireplace** [comment]
Anyways, I don't see any possible way to do this using scroll wheel without either making a PR to forge or turning this in to a coremod. Neither of which are great options.
I suggest we make it possible to get the item using right click instead, unless something else is going to happen when we right click it.

**Comment by MrIbby** [comment]
This might be possible by overriding `Entity.getPickedResult(RayTraceResult)`
