### ISSUE TITLE
Add smoker block.

### ISSUE THREAD

**Issue by Anaghold** [EversongMill/Genesis#74]
- Smoker work underwater.
- It has a model.
- It eject black hot water particles (and more rarely white hot water particles).
- It make damage (as fire) when the player swim in particles.
- It generate in deep ocean (only).

https://www.kunstnet.de/w3/11988/gross_black-smoker-v2.jpg

**Comment by The-Fireplace** [comment]
![image](https://cloud.githubusercontent.com/assets/5914284/26525665/2415319a-4324-11e7-8e60-b7503783ef40.png)
First take on the model. Thoughts?
